CREATE PROCEDURE FI_SP_BuscarPorCPF
    @CPF VARCHAR(14) 
AS
BEGIN
    SET NOCOUNT ON;

    SELECT ID, NOME, SOBRENOME, NACIONALIDADE, CEP, ESTADO, CIDADE, LOGRADOURO, EMAIL, TELEFONE, CPF
    FROM 
        CLIENTES
    WHERE 
        CPF = @CPF;
END;
